### ISSUE TITLE
Can't build 2.1.0 from source for Homebrew

### ISSUE THREAD

**Issue by ilovezfs** [fulldecent/corelocationcli#12]
It seems that the formula for Homebrew is unable to build the latest release because it's requiring signing certificates and developer identities to be set up. So for now the Homebrew version is stuck on 2.0.0.

See https://github.com/Homebrew/homebrew-core/pull/4716.

Formula file is here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/corelocationcli.rb

**Comment by fulldecent** [comment]
Thanks for the report.

I am not sure how to fix this issue. Is any advice available?

**Comment by ilovezfs** [comment]
It doesn't affect 2.0.0 so you could git bisect the issue to find exactly what "broke" it.

**Comment by fulldecent** [comment]
The validation testing here has a broken link:
https://github.com/Homebrew/homebrew-core/pull/4716/commits

Do you know how I am able to find the test that failed so I can run a bisect? Thank you.

**Comment by ilovezfs** [comment]
I'll re-run the job :)

**Comment by ilovezfs** [comment]
it's running now https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8776/

**Comment by fulldecent** [comment]
Thank you, I will try to make sense of this and resolve it.

**Comment by ilovezfs** [comment]
The three logs are

10.12
https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8776/version=sierra/console

10.11
https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8776/version=el_capitan/console

10.10
https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8776/version=yosemite/console

**Comment by fulldecent** [comment]
Fixed, we switched to Homebrew Cask. Thank you!

https://github.com/caskroom/homebrew-cask/pull/31827

**Comment by ilovezfs** [comment]
@fulldecent you're welcome! Thanks for taking care of this.
