### ISSUE TITLE
version 2.0.0 seems to ignore format string

### ISSUE THREAD

**Issue by sneak** [fulldecent/corelocationcli#13]
```
sneak@pris:~$ CoreLocationCLI -once YES -format '{ "lat": %latitude, "lon": %longitude }'
<+37.REDACTED,-80.REDACTED> +/- 134.13m (speed -1.00 mps / course -1.00) @ 10/8/16, 00:05:58 Eastern Daylight Time
```

**Comment by sneak** [comment]
```

sneak@pris:~$ CoreLocationCLI -once yes -format '%latitude : %longitude'
works
sneak@pris:~$ CoreLocationCLI -once yes -format 'x %latitude : %longitude'
works
sneak@pris:~$ CoreLocationCLI -once yes -format '"lat" %latitude : %longitude'
fails
sneak@pris:~$ CoreLocationCLI -once yes -format 'lat %latitude : %longitude'
works
sneak@pris:~$ CoreLocationCLI -once yes -format '{ lat %latitude : %longitude'
fails
```

**Comment by sneak** [comment]
really would defaulting to json output be so bad?

**Comment by fulldecent** [comment]
Hmmm interesting that the other ones work but that one fails.

I would love JSON output everywhere. But convention seems to be that command line tools do not output JSON. Maybe we can make a `-json` option, but it would have to be streaming json.

**Comment by sneak** [comment]
Convention is wrong now that `jq -r` exists. Also, I always use `-once`.

**Comment by fulldecent** [comment]
That makes sense, `-json` can imply `-once`. I'm not sure how `jq -r` works.

**Comment by derhuerst** [comment]
> I'm not sure how `jq -r` works.

@fulldecent See [the manual for `jq`](https://stedolan.github.io/jq/manual/).

@sneak I don't think `jq` can be considered a standard/convention by now. It is still far too unknown.

**Comment by derhuerst** [comment]
Why doesn't `CoreLocationCLI` output all information via JSON (like accuracy, speed, direction)?

**Comment by derhuerst** [comment]
> Why doesn't `CoreLocationCLI` output all information via JSON (like accuracy, speed, direction)? Right now, `-json` is a showstopper for me because it doesn't give me accuracy.

bump.

**Comment by derhuerst** [comment]
Also, it seems like you made backwards-incompatible changes with `v2.2.0` 😢
