### ISSUE TITLE
Submit to Homebrew Cask [HELP WANTED]

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/corelocationcli#14]
This app needs to be signed because of the location services. So it appears it will fail in newer versions of normal homebrew and the newest version of macOS.

We will need to submit the binary to https://github.com/caskroom/homebrew-cask

This seems difficult, especially because this is a command line app, not a `.app`.

---

Please help with this task if you know how to submit a cask. Here is a start with the information I already have.

Specifically I don't know which stanza (https://github.com/caskroom/homebrew-cask/tree/master/doc/cask_language_reference/stanzas) to use for installing a command line program. That and it would really be helpful if someone with experience can review this and submit.

``` ruby
cask 'corelocationcli' do
  version '2.2.0'
  sha256 'fb59410ee9182c2616303c21f19c783a8afe852b16170dfe3894b0c461bf541e'

  # https://github.com/fulldecent/corelocationcli was verified as official when first introduced to the cask
  url "https://github.com/fulldecent/corelocationcli/releases/download/#{version}/CoreLocationCLI.zip"
  appcast 'https://github.com/fulldecent/corelocationcli/releases.atom',
          checkpoint: 'c31d218a45a4f8e685e573c441ac72aa5c53f68e9966736e95f4f3aab51b927d'
  name 'Core Location CLI'
  homepage 'https://github.com/fulldecent/corelocationcli'
end
```

**Comment by fulldecent** [comment]
Reference: #11, #12

**Comment by jawshooah** [comment]
@fulldecent The stanza you're looking for is `binary 'CoreLocationCLI'`. Feel free to submit a PR when ready :+1:

**Comment by fulldecent** [comment]
Thank you, added here https://github.com/caskroom/homebrew-cask/pull/31827

**Comment by fulldecent** [comment]
Fixed here https://github.com/caskroom/homebrew-cask/pull/31827
