### ISSUE TITLE
broken JSON output

### ISSUE THREAD

**Issue by derhuerst** [fulldecent/corelocationcli#19]
A multi-line address in the JSON output breaks it. Valid JSON requires line breaks to be encoded.

In general, it's considered bad practice not to encode JSON. Always encode it using a library/builtin.

**Comment by derhuerst** [comment]
An example:

```json
{
  "latitude": 1.234,
  "longitude": 4.321,
  "altitude": 1234,
  "direction": -1.0,
  "speed": -1,
  "h_accuracy": 72,
  "v_accuracy": 12,
  "time": "2018-02-06 19:10:42 +0000",
  "address": "Some Road 12
12345 Some City
Germany"
}
```

**Comment by derhuerst** [comment]
FYI kiliankoe/location is an alternative that has correct json encoding.

**Comment by fulldecent** [comment]
Thank you. Yes, valid issue.

**Comment by JayBrown** [comment]
Noticed the same today. Until now I had only used default output, then used mapbox for address. But then I tried the `-json` option, and it didn't work:

```
CoreLocationCLI -json | jq -r '.latitude'
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 12, column 8
```

**Comment by fulldecent** [comment]
Fixed in latest version. Requesting testing.
