### ISSUE TITLE
[BUG] newline not working in -format output (v3.1.0)

### ISSUE THREAD

**Issue by JayBrown** [fulldecent/corelocationcli#24]
`CoreLocationCLI -format "%latitude %longitude\n%address"` doesn't add a newline after the longitude.

**Comment by fulldecent** [comment]
Please see https://stackoverflow.com/questions/3005963/how-can-i-have-a-newline-in-a-string-in-sh

This can be handled as follows:

```sh
CoreLocationCLI -format $'%latitude %longitude\n%address'
```
