### ISSUE TITLE
No need to disable "follow" with JSON output

### ISSUE THREAD

**Issue by purcell** [fulldecent/corelocationcli#25]
With "follow" enabled, the JSON output effectively becomes jsonlines output, which isn't so bad. This means a stream of output with `-json -follow` could usefully be read by another program, so it's not helpful to disable that possibility. In fact, I have a use case for which this behaviour would be ideal.

**Comment by purcell** [comment]
Also thanks for this useful program!

**Comment by fulldecent** [comment]
Thank you, good suggestion. Fixing this is in the project scope.

Also, documentation should be updated to explain that output could be complaint with JSON lines, and will definitely not be compliant with JSON, when using --follow.

Would you like to start a patch for this?

**Comment by purcell** [comment]
I can easily do that, but the bigger issue is the currently invalid JSON output noted in #19.

**Comment by fulldecent** [comment]
Fixed in latest version. Requesting testing.

Will need to compile from source because this latest update is not yet in Homebrew.

**Comment by purcell** [comment]
That seems to work, though with `-follow` it seems to update many times per second, even when the location data isn't changing, and then fairly quickly the geocoding API starts rejecting calls, presumably due to rate limiting.

**Comment by fulldecent** [comment]
Thank you, fixed in 4049dad

**Comment by purcell** [comment]
Nice — that works very well!
