### ISSUE TITLE
CoreLocationCLI is not properly notarized - macOS Catalina issue

### ISSUE THREAD

**Issue by Chrede88** [fulldecent/corelocationcli#27]
Just letting you know that CoreLocationCLI won't run in macOS Catalina. Apple demands all applications to be properly notarized by Apple, before they can be executed on a Mac running macOS Catalina.
See this link for further info: https://developer.apple.com/news/?id=10032019a

**Comment by fulldecent** [comment]
Thank you for explaining. I'm not exactly sure how to follow those instructions from Apple but here is what I have done:

1. New Xcode project (with Xcode 11.1)
2. Copy in the old code
3. Target > Signing & Capabilities > Resource > Location
4. Product > Archive
5. Export built product
6. Upload binary here

[CoreLocationCLI.zip](https://github.com/fulldecent/corelocationcli/files/3731782/CoreLocationCLI.zip)

This should be a signed binary and I am hoping it is notarized as required.

If anybody with Catalina could please test it, could you please say how you can confirm if it is working?

**Comment by Chrede88** [comment]
Just tested it. Still not working!
I can't say I'm an expert in any way. Haven't been through the process myself.
I found this link that seem to explain the process: https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

Hope it helps:)

**Comment by Chrede88** [comment]
It actually does work!:) My bad.
After trying to executing it the first time, go to `System Pref --> Security & Privacy --> General` and click in the bottom right corner to allow `CoreLocationCLI` to run. Execute it ones more, it should now run.
