### ISSUE TITLE
A new release is needed. v2.0.0

### ISSUE THREAD

**Issue by adaofeliz** [fulldecent/corelocationcli#4]
The latest release CoreLocationCLI 1.0.0 is from Aug 27, 2014 - 4 commits to master since this release.
This is important so that a homebrew formula can be created. 
No binary files needed, just code will be fine.

**Comment by fulldecent** [comment]
New release created

**Comment by adaofeliz** [comment]
Thanks - New pullrequest for homebrew created https://github.com/Homebrew/homebrew/pull/43759
