### ISSUE TITLE
Documentation: Privacy change for Big Sur (11.x)

### ISSUE THREAD

**Issue by waylonis** [fulldecent/corelocationcli#40]
For me, I had to go into Settings > Security & Privacy and select the Privacy tab. CoreLocationCLI was listed, but disabled. Clicking on the lock in the lower left let me check the box next to the tool. Worked perfectly after that.

**Comment by fulldecent** [comment]
Thank you, Added note to error message at https://github.com/fulldecent/corelocationcli/commit/1ee12638be83e4c7274ade50f23a11aba7c52557#diff-13f7db93b7b5f7772cf5cf107e42a8305300be171d29e8dbdbf5241fb9873458R132
