### ISSUE TITLE
CoreLocationCLI 4.0.0 seems to have broken json output and is having weird permissions issues

### ISSUE THREAD

**Issue by myriadtim** [fulldecent/corelocationcli#43]
Monterey 12.3.1
CoreLocation 4.0.0

corelocationcli -j produces:

638 bytes, no JSON object

once I close a terminal window, corelocationcli permissions seem to vanish from preferences.
This seems a regression from the prior release but I don't have it to test.

**Comment by seandenigris** [comment]
I confirm the broken JSON option on macOS 12.4. 

I also experienced the permission issue, but moving the binary under `/Applications` fixed it

**Comment by kamidev** [comment]
M1 Mac with macOS 12.4. Confirm JSON option is broken. Couldn't reproduce the permission issues.

**Comment by sametcodes** [comment]
M1 Mac with macOS 12.1 (21C52), I confirm too JSON option is broken.
