### ISSUE TITLE
Update readme to reflect new options

### ISSUE THREAD

**Issue by jsejcksn** [fulldecent/corelocationcli#44]
@fulldecent It looks like lines 9 to 79 in the readme didn't get updated in the latest release; it still shows the outdated options information:

https://github.com/fulldecent/corelocationcli/blob/1ee12638be83e4c7274ade50f23a11aba7c52557/README.md?plain=1#L9-L79

**Comment by fulldecent** [comment]
Thank you, fixed at https://github.com/fulldecent/corelocationcli/commit/6243128deccdedc5d028e68801afc0d1e344a96f
