### ISSUE TITLE
LOCATION MANAGER ERROR: The operation couldn’t be completed. (kCLErrorDomain error 1.)

### ISSUE THREAD

**Issue by fanlessfan** [fulldecent/corelocationcli#48]
I am using macOS Ventura. how to grant the location access to corelocationcli? I can grant it with pre-Ventura, but can't find it in Ventura. thx

**Comment by n8henrie** [comment]
Same here. Have been tinkering for days with different variations on embedding `Info.plist` into the binary, `codesign --force -s - --entitlements entitlements.plist mybinary`, no luck. I can create a new XCode project as an "app" and with both Swift and ObjC get CLLocation to work fine, but if I instead choose "command line tool" as the project type, using the same basic code, I can't get it working no matter what I try -- the permissions prompt never come up.

**Comment by jlconlin** [comment]
Another one here. Please let us know how to make this work.

**Comment by jlconlin** [comment]
Another one here. Please let us know how to make this work.

**Comment by jtsigros** [comment]
goto discussion:
https://github.com/fulldecent/corelocationcli/issues/46

in particular look at JayBrown post we got it working, I have the manual way and JayBrown as developed a script to fix this

**Comment by fulldecent** [comment]
Please continue at https://github.com/fulldecent/corelocationcli/issues/46

I have resigned binary and reuploaded (pending Brew review) hopefully that may fix
