### ISSUE TITLE
Running From .plist

### ISSUE THREAD

**Issue by philtec2** [fulldecent/corelocationcli#49]
macbook pro Monterey 12.6.7
.plist calls the bash script that runs CoreLocationCLI and puts output into a variable and writes to a file. Bash script runs fine on its own. Added a echo "Boo" to the script and prints fine in the file. Your app is called a=$(corelocationcli) as i said works fine when either a user account calls the script or root. Im not sure if the system user (i thought it was a high level user like root) calls the script which calls your app (by the way exchanged CoreLocationCLI  for ls -l and that printed ok im lost now dont know why it wouldn't run from a .plist maybe you can help.

petergreen28a@gmail.com

**Comment by fulldecent** [comment]
Please direct questions like this on stackoverflow
