### ISSUE TITLE
Does not work on El Capitan (kCLErrorDomain error 0)

### ISSUE THREAD

**Issue by AnthonyMyatt** [fulldecent/corelocationcli#6]
Trying to run CoreLocationCLI I get the following error:
ERROR: The operation couldn’t be completed. (kCLErrorDomain error 0.)

And the following error in the console:
com.apple.xpc.launchd[1]: (com.apple.CoreLocationAgent[1444]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.CoreLocation.agent

WiFi is turned on.

**Comment by fulldecent** [comment]
Hmm. Are you using the binary or the sources?

**Comment by derhuerst** [comment]
For me the [binary from release `2.0.0`](https://github.com/fulldecent/corelocationcli/releases/download/2.0.0/CoreLocationCLI.zip) worked.

**Comment by fulldecent** [comment]
Is anyone else able to reproduce this?

**Comment by fulldecent** [comment]
Closing, not enough information to reproduce.
